object TestLibs {
	const val roomTesting = "androidx.room:room-testing:${Versions.room}"
	const val navigationTest = "androidx.navigation:navigation-testing:${Versions.navigation}"
	const val jUnit = "junit:junit:${Versions.junit}"
	const val mockito = "org.mockito:mockito-core:${Versions.mockito}"
	const val mockk = "io.mockk:mockk:${Versions.mockk}"
	const val mockkAndroid = "io.mockk:mockk-android:${Versions.mockk}"
	const val testRunner = "androidx.test:runner:${Versions.testRunner}"
	const val testRules = "androidx.test:rules:${Versions.testRunner}"
	const val testOrchestrator = "androidx.test:orchestrator:${Versions.testRunner}"
	const val testExt = "androidx.test.ext:junit:${Versions.testExt}"
	const val mockitoKotlin = "com.nhaarman.mockitokotlin2:mockito-kotlin:${Versions.mockitoKotlin}"
	const val espressoCore = "androidx.test.espresso:espresso-core:${Versions.espresso}"
	const val lifeCycleTest = "androidx.arch.core:core-testing:2.1.0"
	const val workManager = "androidx.wo2.2.0rk:work-testing:${Versions.workManager}"
	const val mockWebServer = "com.squareup.okhttp3:mockwebserver:${Versions.mockWebServerVersion}"
	const val testJodaTime = "joda-time:joda-time:${Versions.testJodaTimeVersion}"
	const val paging = "androidx.paging:paging-common-ktx:${Versions.paging}"
}
