name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    name: Run Unit Tests and Check Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Lint Check
        run: ./gradlew lint lintKotlin
      - name: Run Unit Test
        run: ./gradlew test --stacktrace
      - name: Upload app report
        uses: actions/upload-artifact@v1
        with:
          name: reports-app
          path: app/build/reports
      - name: Upload provider report
        uses: actions/upload-artifact@v1
        with:
          name: reports-provider
          path: provider/build/reports



  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build App
        run: ./gradlew build
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: app/build/outputs/apk/debug/app-debug.apk