name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    name: Run Unit Tests and Check Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Lint Check
        run: ./gradlew lint lintKotlin
      - name: Run Unit Test
        run: ./gradlew test --stacktrace
      - name: Run Coverage and Verification
        run: ./gradlew jacocoFullReport


  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build App
        run: ./gradlew build
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk